---

- name: install new jail
  hosts: jail_hosts
  become: yes
  become_method: sudo
  pre_tasks:
    - assert:
        that: JAIL_NAME is match("^j\d{3}$")
  # roles:
  #   - jail_hosts
  tasks:
    - set_fact:
        JAIL_DIR: "{{ JAILS_DIR }}/{{ JAIL_NAME }}"
        EPAIR_NUM: "{{ JAIL_NAME | regex_search('0*(\\d+)$', '\\1') | first }}"
        HOSTNAME: "{{ ansible_facts['nodename'] }}"
    - name: Create and extract to jail dir
      shell: "mkdir -p {{ JAIL_DIR }} &&
        curl {{ BASE_TAR_URL }} | tar -C {{ JAIL_DIR }} -xf -"
      args:
        warn: false
        creates: "{{ JAIL_DIR }}"
    - name: ensure jail config entry present
      blockinfile:
        path: "{{ JAIL_CONF_PATH }}"
        block: "{% include 'roles/jail_hosts/templates/jail.conf.j2' %}"
        marker: "# {mark} ANSIBLE BLOCK FOR {{ JAIL_DIR }}"
    - name: configure DHCP
      lineinfile:
        path: "{{ JAIL_DIR }}/etc/rc.conf"
        state: present
        create: yes
        line: "ifconfig_epair{{ EPAIR_NUM }}b=\"SYNCDHCP\""
    - name: configure ssh service
      lineinfile:
        path: "{{ JAIL_DIR }}/etc/rc.conf"
        state: present
        line: 'sshd_enable="YES"'
    - name: configure crash dumps
      lineinfile:
        path: "{{ JAIL_DIR }}/etc/rc.conf"
        state: present
        line: 'dumpdev="NO"'
    - name: configure insecure ssh
      blockinfile:
        path: "{{ JAIL_DIR }}/etc/ssh/sshd_config"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR INSECURE SSH"
        block: |
          PasswordAuthentication yes
          PermitEmptyPasswords yes
          PermitRootLogin yes
        state: present
    - name: Ensure insecure jail is started
      shell: "jail -c {{ JAIL_NAME }}"
