---

- name: install new jail
  hosts: jail-hosts
  remote_user: user
  become: yes
  become_method: sudo
  tasks:
    - shell: "mkdir {{ JAILS_BASE }}/{{ JAIL_NAME }}"
      args:
        executable: /usr/local/bin/zsh
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}"
    - shell: "wget -O - -o /dev/null {{ REPOSITORY_PATH }} | tar -xf -C {{ JAILS_BASE }}/{{ JAIL_NAME }}"
      args:
        executable: /usr/local/bin/zsh
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}"
