---

- name: install new jail
  hosts: jail_hosts
  remote_user: user
  become: yes
  become_method: sudo
  vars:
    - HOSTNAME: hostname.stdout
  tasks:
    - name: Check out hostname
      shell: hostname
      register: hostname
      changed_when: false
    - name: Create and extract jail dir
      shell: "mkdir -p {{ JAILS_BASE }}/{{ JAIL_NAME }} &&
        wget -O - -o /dev/null {{ REPOSITORY_PATH }} |
        tar -C {{ JAILS_BASE }}/{{ JAIL_NAME }} -xf -"
      args:
        warn: false
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}"
    - set_fact:
        EPAIR_NUM: "{{ JAIL_NAME | regex_search('0*(\\d+)$', '\\1') | first }}"
    - blockinfile:
        path: "{{ JAIL_CONF_PATH }}"
        block: "{% include './assets/jail.conf.j2' %}"
  pre_tasks:
    - assert:
        that: JAIL_NAME is match("^j\d{3}$")
