---

- name: install new jail
  hosts: jail_hosts
  become: yes
  become_method: sudo
  tasks:
    - name: Check out hostname
      shell: hostname
      register: hostname
      changed_when: false
    - set_fact:
        EPAIR_NUM: "{{ JAIL_NAME | regex_search('0*(\\d+)$', '\\1') | first }}"
        HOSTNAME: "{{ hostname.stdout }}"
    - name: Create and extract to jail dir
      shell: "mkdir -p {{ JAILS_BASE }}/{{ JAIL_NAME }} &&
        curl file:///usr/dist/base-jail_20190827.txz | tar -C {{ JAILS_BASE }}/{{ JAIL_NAME }} -xf -"
      args:
        warn: false
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}"
    - blockinfile:
        path: "{{ JAIL_CONF_PATH }}"
        block: "{% include 'assets/jail.conf.j2' %}"
        marker: "# {mark} ANSIBLE BLOCK FOR {{ JAILS_BASE }}/{{ JAIL_NAME }}"
    - name: configure DHCP
      lineinfile:
        path: "{{ JAILS_BASE }}/{{ JAIL_NAME }}/etc/rc.conf"
        state: present
        line: "ifconfig_epair{{ EPAIR_NUM }}b=\"SYNCDHCP\""
    - name: configure insecure ssh
      blockinfile:
        path: "{{ JAILS_BASE }}/{{ JAIL_NAME }}/etc/ssh/sshd_config"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR INSECURE SSH"
        block: |
          PasswordAuthentication yes
          PermitEmptyPasswords yes
          PermitRootLogin yes
        state: present
    - name: Ensure insecure jail is started
      shell: "jail -c {{ JAIL_NAME }}"
  pre_tasks:
    - assert:
        that: JAIL_NAME is match("^j\d{3}$")
