---

- name: install new jail
  hosts: jail_hosts
  become: yes
  become_method: sudo
  pre_tasks:
    - assert:
        that: JAIL_NAME is match("^j\d{3}$")
  roles:
    - jail_hosts
  tasks:
    - set_fact:
        EPAIR_NUM: "{{ JAIL_NAME | regex_search('0*(\\d+)$', '\\1') | first }}"
        HOSTNAME: "{{ ansible_facts['nodename'] }}"
    - name: Create and extract to jail dir
      shell: "mkdir -p {{ JAILS_DIR }}/{{ JAIL_NAME }} &&
        curl {{ BASE_JAIL_TAR_URL }} | tar -C {{ JAILS_DIR }}/{{ JAIL_NAME }} -xf -"
      args:
        warn: false
        creates: "{{ JAILS_DIR }}/{{ JAIL_NAME }}"
    - blockinfile:
        path: "{{ JAIL_CONF_PATH }}"
        block: "{% include 'jail.conf.j2' %}"
        marker: "# {mark} ANSIBLE BLOCK FOR {{ JAILS_DIR }}/{{ JAIL_NAME }}"
    - name: configure DHCP
      lineinfile:
        path: "{{ JAILS_DIR }}/{{ JAIL_NAME }}/etc/rc.conf"
        state: present
        line: "ifconfig_epair{{ EPAIR_NUM }}b=\"SYNCDHCP\""
    - name: configure insecure ssh
      blockinfile:
        path: "{{ JAILS_DIR }}/{{ JAIL_NAME }}/etc/ssh/sshd_config"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR INSECURE SSH"
        block: |
          PasswordAuthentication yes
          PermitEmptyPasswords yes
          PermitRootLogin yes
        state: present
    - name: Ensure insecure jail is started
      shell: "jail -c {{ JAIL_NAME }}"
