---

- name: install new jail
  hosts: jail_hosts
  remote_user: user
  become: yes
  become_method: sudo
  tasks:
    - shell: "mkdir -p {{ JAILS_BASE }}/{{ JAIL_NAME }} &&
        wget -O - -o /dev/null {{ REPOSITORY_PATH }} |
        tar -C {{ JAILS_BASE }}/{{ JAIL_NAME }} -xf -"
      args:
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}"
        warn: false
