---

- name: install new jail
  hosts: jail_hosts
  remote_user: user
  become: yes
  become_method: sudo
  tasks:
    - name: Check out hostname
      shell: hostname
      register: hostname
      changed_when: false
    - set_fact:
        EPAIR_NUM: "{{ JAIL_NAME | regex_search('0*(\\d+)$', '\\1') | first }}"
        HOSTNAME: "{{ hostname.stdout }}"
    - name: Create and extract to jail dir
      shell: "mkdir -p {{ JAILS_BASE }}/{{ JAIL_NAME }} &&
        wget -O - -o /dev/null {{ REPOSITORY_PATH }} |
        tar -C {{ JAILS_BASE }}/{{ JAIL_NAME }} -xf -"
      args:
        warn: false
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}"
    - blockinfile:
        path: "{{ JAIL_CONF_PATH }}"
        block: "{% include 'assets/jail.conf.j2' %}"
        marker: "# {mark} ANSIBLE BLOCK FOR {{ JAILS_BASE }}/{{ JAIL_NAME }}"
    - name: configure DHCP
      lineinfile:
        path: "{{ JAILS_BASE }}/{{ JAIL_NAME }}/etc/rc.conf"
        state: present
        line: "ifconfig_epair{{ EPAIR_NUM }}b=\"SYNCDHCP\""
    - name: Install sudo
      shell: "export ASSUME_ALWAYS_YES=\"YES\" && pkg -y -r {{ JAILS_BASE }}/{{ JAIL_NAME }} install sudo"
      args:
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}/usr/local/bin/sudo"
        executable: /usr/local/bin/zsh
    - name: Install zsh
      shell: "export ASSUME_ALWAYS_YES=\"YES\" && pkg -y -r {{ JAILS_BASE }}/{{ JAIL_NAME }} install zsh"
      args:
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}/usr/local/bin/zsh"
        executable: /usr/local/bin/zsh
    - name: Create user
      shell: "jail -c {{ JAIL_NAME }} || true;
        jexec {{ JAIL_NAME }} pw useradd user -m -s /usr/local/bin/zsh || true"
    - name: add user to passwordless sudo
      copy:
        src: "assets/sudoers"
        dest: "{{ JAILS_BASE }}/{{ JAIL_NAME }}/usr/local/etc/sudoers"
        mode: "440"
        owner: root
        group: wheel
    - name: Create .ssh directory
      file:
        path: "{{ JAILS_BASE }}/{{ JAIL_NAME }}/home/user/.ssh"
        state: directory
        mode: "660"
    - name: Append public key to user's authorized_keys
      authorized_key:
        user: user
        state: present
        key: " {{ lookup('file', JAIL_ADMIN_SSH_KEY_FILE) }}"
        path: "{{ JAILS_BASE }}/{{ JAIL_NAME }}/home/user/.ssh/authorized_keys"
  pre_tasks:
    - assert:
        that: JAIL_NAME is match("^j\d{3}$")
