---

- name: install new jail
  hosts: jail_hosts
  remote_user: user
  become: yes
  become_method: sudo
  vars:
    - HOSTNAME: hostname.stdout
  tasks:
    - shell: hostname
      register: hostname
    - shell: "mkdir -p {{ JAILS_BASE }}/{{ JAIL_NAME }} &&
        wget -O - -o /dev/null {{ REPOSITORY_PATH }} |
        tar -C {{ JAILS_BASE }}/{{ JAIL_NAME }} -xf -"
      name: create jail directory
      args:
        creates: "{{ JAILS_BASE }}/{{ JAIL_NAME }}"
        warn: false
    - blockinfile:
        name: create jail config
        path: "{{ JAIL_CONF_PATH }}"
        block: "{% include './assets/jail.conf.j2' %}"
