---

- name: removes jail
  hosts: jail_hosts
  become: yes
  become_method: sudo
  pre_tasks:
    - assert:
        that:
          - JAIL_NAME is match("^j\d{3}$")
          - I_KNOW_WHAT_I_AM_DOING == true
  tasks:
    - set_fact:
        JAIL_DIR: "{{ JAILS_DIR }}/{{ JAIL_NAME }}"
    - name: stop jail
      shell: "jail -r {{ JAIL_NAME }} || true"
    - name: remove jail dir
      shell: "chflags -R noschg {{ JAIL_DIR }} && rm -rdf {{ JAIL_DIR }}"
      args:
        executable: /usr/local/bin/zsh
        removes: "{{ JAIL_DIR }}"
    - name: ensure block in file is absent
      blockinfile:
        dest: "{{ JAIL_CONF_PATH }}"
        marker: "# {mark} ANSIBLE BLOCK FOR {{ JAIL_DIR }}"
        state: absent
