---

- name: removes jail
  hosts: jail_hosts
  remote_user: user
  become: yes
  become_method: sudo
  tasks:
    - name: stop jail
      shell: "jail -r {{ JAIL_NAME }}"
    - name: remove jail dir
      shell: "chflags -R noschg {{ JAILS_BASE }}/{{ JAIL_NAME }} && rm -rdf {{ JAILS_BASE }}/{{ JAIL_NAME }}"
      args:
        executable: /usr/local/bin/zsh
        removes: "{{ JAILS_BASE }}/{{ JAIL_NAME }}"
    - blockinfile:
        dest: "{{ JAIL_CONF_PATH }}"
        marker: "# {mark} ANSIBLE BLOCK FOR {{ JAILS_BASE }}/{{ JAIL_NAME }}"
        state: absent
