---

- name: install php and extensions
  package:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - php73
    - php73-extensions
    - php73-openssl
    - php73-pecl-imagick
    - php73-pecl-memcached
    - php73-pecl-redis
    - php73-zip
    - php73-fileinfo
    - php73-mbstring
    - php73-pdo
    - php73-pdo_mysql
    - php73-pdo_sqlite
    - php73-pear-Mail_Mime
    - php73-pear-Mail
    - php73-curl
    - php73-fileinfo
- name: 
  template:
    src: "templates/php.ini.j2"
    dest: /usr/local/etc/php.ini
  become: yes
