---

- name: install postgres11-server
  package:
    name: postgresql11-server
    state: present
  become: yes
- name: install postgres11-client
  package:
    name: postgresql11-client
    state: present
  become: yes
- name: configure encoding
  blockinfile:
    path: "/etc/login.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR POSTGRESQL"
    block: |
      postgres:\
        :lang=en_US.UTF-8:\
        :setenv=LC_COLLATE=C:\
        :tc=default:
  become: yes
- name: rebuild login db
  shell: cap_mkdb /etc/login.conf
  become: yes
- name: setting postgres login class
  shell: "sysrc postgresql_class=\"postgres\""
  become: yes
- name: enable postgres service
  service:
    name: postgresql
    enabled: yes
  become: yes
- name: init postgres db
  shell: /usr/local/etc/rc.d/postgresql initdb
  args:
    creates: /var/db/postgres/data11
  become: yes
- name: start postgres service
  service:
    name: postgresql
    state: started
  become: yes
- name: enable listen all connections
  blockinfile:
    path: "/var/db/postgres/data11/postgresql.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR POSTGRESQL LISTEN"
    block: |
      listen_addresses = '*'
  become: yes
- name: restart postgres service
  service:
    name: postgresql
    state: restarted
  become: yes
