---

- name: install nginx
  package:
    name: nginx
    state: present
  become: yes
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
- name: create vhosts directory
  file:
    path: /usr/local/etc/nginx/vhosts
    state: directory
  become: yes
- name: create sites directory
  file:
    path: /usr/local/www/sites
    state: directory
    owner: www
    group: www
  become: yes
- name: copy php-fpm config
  template:
    dest: "/usr/local/etc/php-fpm.d/www.conf"
    src: "templates/php-fpm.www.conf.j2"
  become: yes
- name: start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes
  become: yes
- name: copy nginx config
  template:
    src: "templates/nginx.conf.j2"
    dest: "/usr/local/etc/nginx/nginx.conf"
  become: yes
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
